// Pre-projects the US state outlines into SVG paths at build time so the browser
// ships zero geo libraries. Also verifies every site pin lands inside the state
// its record claims, which is the only automated check we have on the coordinates.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { geoAlbersUsa, geoMercator, geoPath, geoContains } from "d3-geo";
import { feature } from "topojson-client";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const topo = require("us-atlas/states-10m.json");

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

// Canonical d3 albersUsa framing for a 975 x 610 viewBox.
export const VIEW_W = 975;
export const VIEW_H = 610;
const projection = geoAlbersUsa().scale(1300).translate([VIEW_W / 2, VIEW_H / 2]);
const pathGen = geoPath(projection);

const states = feature(topo, topo.objects.states);

// FIPS -> USPS. Needed because states-10m carries FIPS ids only.
const FIPS_TO_ABBR = {
  "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO", "09": "CT",
  "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI", "16": "ID", "17": "IL",
  "18": "IN", "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME", "24": "MD",
  "25": "MA", "26": "MI", "27": "MN", "28": "MS", "29": "MO", "30": "MT", "31": "NE",
  "32": "NV", "33": "NH", "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
  "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA", "54": "WV",
  "55": "WI", "56": "WY", "60": "AS", "66": "GU", "69": "MP", "72": "PR", "78": "VI",
};

const out = [];
for (const f of states.features) {
  const abbr = FIPS_TO_ABBR[f.id];
  if (!abbr) continue;
  const d = pathGen(f);
  // albersUsa returns null geometry for territories outside its composite frame.
  if (!d) continue;
  const c = pathGen.centroid(f);
  out.push({
    abbr,
    name: f.properties.name,
    d,
    cx: Number.isFinite(c[0]) ? +c[0].toFixed(1) : null,
    cy: Number.isFinite(c[1]) ? +c[1].toFixed(1) : null,
  });
}
out.sort((a, b) => a.abbr.localeCompare(b.abbr));

const ts = `// GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source: us-atlas@3 states-10m (public domain, US Census cartographic boundaries),
// projected with d3-geo geoAlbersUsa().scale(1300) into a ${VIEW_W}x${VIEW_H} viewBox.
export const VIEW_W = ${VIEW_W};
export const VIEW_H = ${VIEW_H};
export type StateShape = { abbr: string; name: string; d: string; cx: number | null; cy: number | null };
export const US_STATES: StateShape[] = ${JSON.stringify(out)};
`;
fs.mkdirSync(path.join(root, "src/lib"), { recursive: true });
fs.writeFileSync(path.join(root, "src/lib/us-states.generated.ts"), ts);
console.log(`wrote src/lib/us-states.generated.ts with ${out.length} states`);

// ---- verification pass ----------------------------------------------------
const seedPath = path.resolve(root, "data/sites.seed.json");
if (fs.existsSync(seedPath)) {
  const seed = JSON.parse(fs.readFileSync(seedPath, "utf8"));
  const byAbbr = new Map(states.features.map((f) => [FIPS_TO_ABBR[f.id], f]));
  let ok = 0;
  const problems = [];
  for (const s of seed.sites) {
    if (s.lat == null || s.lng == null) {
      problems.push(`${s.slug}: no coordinates (expected, coord_precision=${s.coord_precision})`);
      continue;
    }
    const f = byAbbr.get(s.state);
    if (!f) { problems.push(`${s.slug}: unknown state ${s.state}`); continue; }
    const inside = geoContains(f, [s.lng, s.lat]);
    const xy = projection([s.lng, s.lat]);
    if (!inside) problems.push(`${s.slug}: (${s.lat}, ${s.lng}) is NOT inside ${s.state}`);
    else if (!xy) problems.push(`${s.slug}: projects outside the albersUsa frame`);
    else ok++;
  }
  console.log(`\nPIN VERIFICATION: ${ok}/${seed.sites.length} pins land inside their stated state.`);
  for (const p of problems) console.log("  - " + p);
  const hardFails = problems.filter((p) => p.includes("NOT inside") || p.includes("unknown state") || p.includes("outside the albersUsa"));
  if (hardFails.length) { console.error("\nFAILED: coordinates disagree with stated states."); process.exit(1); }
}

// ---- Europe country outlines (world-atlas) ---------------------------------
const worldTopo = require("world-atlas/countries-110m.json");
const countries = feature(worldTopo, worldTopo.objects.countries);

// ISO 3166-1 numeric ids for Europe (+ nearby for map context)
const EUROPE_NUMERIC = new Set([
  "008","020","040","056","070","100","112","191","196","203","208","233","246",
  "250","268","276","300","336","348","352","372","380","428","438","440","442",
  "470","498","499","528","578","616","620","642","643","674","688","703","705",
  "724","752","756","804","807","826","831","832","833", // GB + crown deps
]);

// Human labels for common codes we care about on the dashboard
const NUMERIC_TO_ISO2 = {
  "826": "GB", "372": "IE", "250": "FR", "276": "DE", "528": "NL", "056": "BE",
  "442": "LU", "040": "AT", "756": "CH", "380": "IT", "724": "ES", "620": "PT",
  "752": "SE", "578": "NO", "208": "DK", "246": "FI", "616": "PL", "203": "CZ",
  "703": "SK", "348": "HU", "642": "RO", "100": "BG", "300": "GR", "191": "HR",
  "705": "SI", "440": "LT", "428": "LV", "233": "EE", "352": "IS", "008": "AL",
  "070": "BA", "499": "ME", "807": "MK", "688": "RS", "792": "TR", "804": "UA",
  "498": "MD", "112": "BY", "643": "RU",
};

const EU_VIEW_W = 975;
const EU_VIEW_H = 610;
// Western/Northern Europe framing — fits GB cluster today, ready for continent rollout
const euProjection = geoMercator()
  .center([-2, 54])
  .scale(1450)
  .translate([EU_VIEW_W / 2, EU_VIEW_H / 2]);
const euPathGen = geoPath(euProjection);

const euOut = [];
for (const f of countries.features) {
  const id = String(f.id).padStart(3, "0");
  if (!EUROPE_NUMERIC.has(id) && !NUMERIC_TO_ISO2[id]) continue;
  // Skip far-east Russia blob for this framing
  if (id === "643") continue;
  const d = euPathGen(f);
  if (!d) continue;
  const c = euPathGen.centroid(f);
  const iso2 = NUMERIC_TO_ISO2[id] || id;
  euOut.push({
    abbr: iso2,
    name: f.properties.name,
    d,
    cx: Number.isFinite(c[0]) ? +c[0].toFixed(1) : null,
    cy: Number.isFinite(c[1]) ? +c[1].toFixed(1) : null,
  });
}
euOut.sort((a, b) => a.abbr.localeCompare(b.abbr));

const euTs = `// GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source: world-atlas@2 countries-110m (Natural Earth), projected with
// d3-geo geoMercator center([-2,54]) scale(1450) into a ${EU_VIEW_W}x${EU_VIEW_H} viewBox.
export const EU_VIEW_W = ${EU_VIEW_W};
export const EU_VIEW_H = ${EU_VIEW_H};
export type EuropeShape = { abbr: string; name: string; d: string; cx: number | null; cy: number | null };
export const EUROPE_COUNTRIES: EuropeShape[] = ${JSON.stringify(euOut)};
`;
fs.writeFileSync(path.join(root, "src/lib/europe-countries.generated.ts"), euTs);
console.log(`wrote src/lib/europe-countries.generated.ts with ${euOut.length} countries`);
