// Pre-projects the US state outlines into SVG paths at build time so the browser
// ships zero geo libraries. Also verifies every site pin lands inside the state
// its record claims, which is the only automated check we have on the coordinates.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { geoAlbersUsa, geoPath, geoContains } from "d3-geo";
import { feature } from "topojson-client";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const topo = require("us-atlas/states-10m.json");

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

// Canonical d3 albersUsa framing for a 975 x 610 viewBox.
export const VIEW_W = 975;
export const VIEW_H = 610;
const projection = geoAlbersUsa().scale(1300).translate([VIEW_W / 2, VIEW_H / 2]);
const pathGen = geoPath(projection);

const states = feature(topo, topo.objects.states);

// FIPS -> USPS. Needed because states-10m carries FIPS ids only.
const FIPS_TO_ABBR = {
  "01": "AL", "02": "AK", "04": "AZ", "05": "AR", "06": "CA", "08": "CO", "09": "CT",
  "10": "DE", "11": "DC", "12": "FL", "13": "GA", "15": "HI", "16": "ID", "17": "IL",
  "18": "IN", "19": "IA", "20": "KS", "21": "KY", "22": "LA", "23": "ME", "24": "MD",
  "25": "MA", "26": "MI", "27": "MN", "28": "MS", "29": "MO", "30": "MT", "31": "NE",
  "32": "NV", "33": "NH", "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND",
  "39": "OH", "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA", "54": "WV",
  "55": "WI", "56": "WY", "60": "AS", "66": "GU", "69": "MP", "72": "PR", "78": "VI",
};

const out = [];
for (const f of states.features) {
  const abbr = FIPS_TO_ABBR[f.id];
  if (!abbr) continue;
  const d = pathGen(f);
  // albersUsa returns null geometry for territories outside its composite frame.
  if (!d) continue;
  const c = pathGen.centroid(f);
  out.push({
    abbr,
    name: f.properties.name,
    d,
    cx: Number.isFinite(c[0]) ? +c[0].toFixed(1) : null,
    cy: Number.isFinite(c[1]) ? +c[1].toFixed(1) : null,
  });
}
out.sort((a, b) => a.abbr.localeCompare(b.abbr));

const ts = `// GENERATED by scripts/build-geo.mjs. Do not edit by hand.
// Source: us-atlas@3 states-10m (public domain, US Census cartographic boundaries),
// projected with d3-geo geoAlbersUsa().scale(1300) into a ${VIEW_W}x${VIEW_H} viewBox.
export const VIEW_W = ${VIEW_W};
export const VIEW_H = ${VIEW_H};
export type StateShape = { abbr: string; name: string; d: string; cx: number | null; cy: number | null };
export const US_STATES: StateShape[] = ${JSON.stringify(out)};
`;
fs.mkdirSync(path.join(root, "src/lib"), { recursive: true });
fs.writeFileSync(path.join(root, "src/lib/us-states.generated.ts"), ts);
console.log(`wrote src/lib/us-states.generated.ts with ${out.length} states`);

// ---- verification pass ----------------------------------------------------
const seedPath = path.resolve(root, "data/sites.seed.json");
if (fs.existsSync(seedPath)) {
  const seed = JSON.parse(fs.readFileSync(seedPath, "utf8"));
  const byAbbr = new Map(states.features.map((f) => [FIPS_TO_ABBR[f.id], f]));
  let ok = 0;
  const problems = [];
  for (const s of seed.sites) {
    if (s.lat == null || s.lng == null) {
      problems.push(`${s.slug}: no coordinates (expected, coord_precision=${s.coord_precision})`);
      continue;
    }
    const f = byAbbr.get(s.state);
    if (!f) { problems.push(`${s.slug}: unknown state ${s.state}`); continue; }
    const inside = geoContains(f, [s.lng, s.lat]);
    const xy = projection([s.lng, s.lat]);
    if (!inside) problems.push(`${s.slug}: (${s.lat}, ${s.lng}) is NOT inside ${s.state}`);
    else if (!xy) problems.push(`${s.slug}: projects outside the albersUsa frame`);
    else ok++;
  }
  console.log(`\nPIN VERIFICATION: ${ok}/${seed.sites.length} pins land inside their stated state.`);
  for (const p of problems) console.log("  - " + p);
  const hardFails = problems.filter((p) => p.includes("NOT inside") || p.includes("unknown state") || p.includes("outside the albersUsa"));
  if (hardFails.length) { console.error("\nFAILED: coordinates disagree with stated states."); process.exit(1); }
}
